language: php

php:
  - 7.2
  - nightly

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - zhifan6797@163.com
    on_success: always
    on_failure: always
